apiVersion: v1
kind: Service
metadata:
name: postgres_exporter #service to provide access to postgreSQL DB on port 5432 and Prometheus exporter on port 9187
labels:
snappyflow/projectname: <yourprojectname>
snappyflow/appname: <yourapplicationname>
spec:
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
  - name: pg-exporter
    protocol: TCP
    port: 9187
    nodePort: 30032
    targetPort: 9187
selector:
app: postgres
