apiVersion: apps/v1
kind: Deployment
metadata:
name: postgres
labels:
snappyflow/projectname: <yourprojectname>
snappyflow/appname: <yourapplicationname>
matchLabels:
app: postgres
snappyflow/projectname: <yourprojectname>
snappyflow/projectname: <yourprojectname>
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:9.6
          ports:
            - name: tcp
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB #container for PostgreSQL DB 
              value: db0
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "postgres-pgdata"
        - name: postgres-exporter #container for Prometheus Exporter for PostgreSQL
          image: bitnami/postgres-exporter
          ports:
           - name: pg-exporter
             containerPort: 9187
          command: ["/bin/sh", "-c"]
        - name: postgreslog #busybox container to forward application logs to stdout
          image: busybox
          args: [/bin/sh, -c, 'tail -n+1 -F /var/log/postgres.log']
          volumeMounts:
          - name: varlog
            mountPath: /var/log/
               
      volumes:
      - name: data
      	emptyDir: {}
 
